#!/bin/sh

if [ $# -ne 1 ]; then
    echo "$0 initial-key-file"
    exit 1
fi

fname=$1

ceph-mon --mkfs -i $(hostname) --keyring "$fname"  --setuser ceph --setgroup ceph
touch /var/lib/ceph/mon/ceph-$(hostname)/sysvinit

/etc/init.d/ceph start mon.$(hostname)
