#!/bin/sh

# Creates the initial keys

if [ $# -ne 1 ]; then
    echo "$0 initial-key-file"
    exit 1
fi

fname=$1

ceph-authtool --create-keyring "$fname" --gen-key -n mon.
ceph-authtool "$fname" --gen-key -n client.admin --set-uid=0 --cap mon 'allow *' --cap osd 'allow *' --cap mds 'allow'
