#!/bin/sh

if [ $# -ne 1 ]; then
    echo "$0 initial-key-file"
    exit 1
fi

fname=$1

ceph-mon --mkfs -i $(hostname) --keyring "$fname"  --setuser ceph --setgroup ceph
touch /var/lib/ceph/mon/ceph-$(hostname)/sysvinit

# Starting with monit, if available
if [ -e /etc/monit ]; then
    /opt/ungleich-tools/monit-ceph-create-start mon.$(hostname)
else
    /etc/init.d/ceph start mon.$(hostname)
fi
